services:
  - type: web
    name: cake-smp-console
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CAKE_SERVER_NAME
        value: Cake SMP
      - key: CAKE_PUBLIC_ADDRESS
        value: e-mep-1.folium.host:25140
      - key: CAKE_STORAGE
        value: sftp
      - key: CAKE_ADMIN_EMAIL
        sync: false
      - key: CAKE_ADMIN_PASSWORD_HASH
        sync: false
      - key: CAKE_RCON_HOST
        sync: false
      - key: CAKE_RCON_PORT
        value: "25575"
      - key: CAKE_RCON_PASSWORD
        sync: false
      - key: CAKE_SFTP_HOST
        sync: false
      - key: CAKE_SFTP_PORT
        value: "2022"
      - key: CAKE_SFTP_USERNAME
        sync: false
      - key: CAKE_SFTP_PASSWORD
        sync: false
      - key: CAKE_SFTP_ROOT
        value: "/"
      - key: CAKE_SMTP_USER
        sync: false
      - key: CAKE_SMTP_PASS
        sync: false
